name: Docker Image for CI for GHCR
on:
  push:

jobs:
  build_and_publish: 
    runs-on: nginx:1.10.1-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Build andpush the image
        run: |
          docker login --username vaishnaviv1105 --password $ {{secrets.GHCR_PAT }} ghcr.io